version: "3.8"

networks:
  frontend:

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d 
      - ./www:/www
    networks:
      - frontend
  php-fpm:
    build: 
      context: .
      dockerfile: FPM-Buster.Dockerfile
    volumes:
      - ./www:/www
    networks:
      - frontend
